# ansible-playbook -i inventory/ playbook/install_openstack.yml
#
- name: Create container host group for OpenStack
  hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Expose instances
      set_fact:
          instances: "{{ instances }}"
      when: hostvars['localhost']['instances'] is undefined
  roles:
    - name: Generate openstack host groups
      role: create_openstack_host_group
  vars_files:
    - "{{ config_file }}"
  tags: always

# TODO: move kolla tasks here